<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Message;
use AppBundle\Interfaces\MessageRepositoryInterface;
use Doctrine\Common\Persistence\ObjectRepository;
use Doctrine\ORM\EntityManagerInterface;

/**
 * MessageRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
final class MessageRepository implements MessageRepositoryInterface
{
    /**
     * @var EntityManagerInterface
     */
    private $entityManager;
    /**
     * @var ObjectRepository
     */
    private $objectRepository;

    /**
     * MessageRepository constructor.
     * @param EntityManagerInterface $entityManager
     */
    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
        $this->objectRepository = $this->entityManager->getRepository(Message::class);
    }

    /**
     * @param int $messageId
     * @return Message|null
     */
    public function findById(int $messageId): ?Message
    {
        return $this->objectRepository->find($messageId);
    }

    /**
     * @param string $sort
     * @return array
     */
    public function findMessages($sort): array
    {
        return $this->objectRepository->findBy([], ['createdAt' => $sort]);
    }

    /**
     * @param Message $message
     */
    public function save(Message $message): void
    {
        $this->entityManager->persist($message);
        $this->entityManager->flush();
    }

    /**
     * @param Message $message
     */
    public function delete(Message $message): void
    {
        $this->entityManager->remove($message);
        $this->entityManager->flush();
    }
}
